<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="LAPTOP-A11EL1IC" name="com.crm.qa.testcases.HomePageTest" tests="6" failures="0" timestamp="13 Feb 2020 12:18:15 GMT" time="35.905" errors="1">
  <testcase name="setUp" time="35.904" classname="com.crm.qa.testcases.HomePageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.crm.qa.pages.LoginPage.loginBtnClick(LoginPage.java:73)
	at com.crm.qa.testcases.HomePageTest.setUp(HomePageTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="verifyLoginBtnclick" time="0.001" classname="com.crm.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- verifyLoginBtnclick -->
  <testcase name="verifyHomePageTitleTest" time="0.000" classname="com.crm.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- verifyHomePageTitleTest -->
  <testcase name="contacts" time="0.000" classname="com.crm.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- contacts -->
  <testcase name="deals" time="0.000" classname="com.crm.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- deals -->
  <testcase name="tasks" time="0.000" classname="com.crm.qa.testcases.HomePageTest">
    <skipped/>
  </testcase> <!-- tasks -->
</testsuite> <!-- com.crm.qa.testcases.HomePageTest -->
